Fix Bad Access when creating predicate in CollectionView scroll until methods
mindbody/Kava pull request #4
Opened 2016-10-13 16:02 UTC by rcgilbert

Defining the types for unused parameters in an NSPredicate evaluation block will trigger a bad access when that predicate is evaluated.  This revision removes those types effectively fixing the `scrollBackwardsUntil(_ block...)` and `scrollForwardUntil(_ block...)` methods.

2016-10-13 16:07 UTC, rcgilbert commented on Kava/Kava/Source/PageObjects/Infrastructure/Elements/CollectionView.swift
> -        let predicate = NSPredicate { (_: Any, _: [String : Any]?) -> Bool in
Note that the types for the parameters passed into an NSPredicate block in Swift 3 are `Any?, [String : Any]?`

2016-10-13 16:10 UTC, johnhammerlund requested changes
Would like your input first; if the parameters aren't required, then the input type of the closure doesn't need to be specified at all imo

2016-10-13 16:10 UTC, Hammertime38 commented on Kava/Kava/Source/PageObjects/Infrastructure/Elements/CollectionView.swift
> +        let predicate = NSPredicate { (_, _) -> Bool in
Could this just be simplified to:
```swift
let predicate = NSPredicate { _ in
...
```

2016-10-13 16:10 UTC, Hammertime38 commented on Kava/Kava/Source/PageObjects/Infrastructure/Elements/CollectionView.swift
> +        let predicate = NSPredicate { (_, _) -> Bool in
Same as above

2016-10-13 17:13 UTC, Hammertime38 commented on Kava/Kava/Source/PageObjects/Infrastructure/Elements/CollectionView.swift
> +        let predicate = NSPredicate { (_, _) -> Bool in
The return type/number of arguments are still specified. See my original suggestion

2016-10-14 14:37 UTC, rcgilbert commented
@Hammertime38 I fixed the things.

2016-10-14 15:48 UTC, johnhammerlund approved these changes

2016-10-14 20:07 UTC, closed without merging